#!/usr/bin/env bash
# Fail if tracked files contain editor/assistant signatures (public-repo gatekeeper).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

FAIL=0
IDE_DOT="$(echo -n Y3Vyc29y | base64 -d)"  # decode at runtime; not stored as plain text in repo

if git ls-files | grep -qE "/\.${IDE_DOT}(/|$)|^\.${IDE_DOT}(/|$)"; then
  echo "FAIL: IDE-only paths are tracked by git — remove them from the index."
  FAIL=1
fi

PATTERNS=(
  "\\.${IDE_DOT}/plans"
  "\\.${IDE_DOT}/rules"
  'Co-authored-by:.*[Aa]gent'
  'Co-authored-by:.*Copilot'
  'Co-authored-by:.*ChatGPT'
  'Co-authored-by:.*Claude'
  'Generated by [Aa]gent'
  'generated by [Aa]gent'
)

while IFS= read -r -d '' file; do
  case "$file" in
    *.css|scripts/check-repo-hygiene.sh|scripts/install-git-hooks.sh|docs/COMMIT_GUIDELINES.md) continue ;;
  esac
  for pat in "${PATTERNS[@]}"; do
    if grep -qE "$pat" "$file" 2>/dev/null; then
      echo "FAIL: $file contains a forbidden assistant/editor signature."
      FAIL=1
      break
    fi
  done
done < <(git ls-files -z)

if [[ "$FAIL" -ne 0 ]]; then
  echo ""
  echo "See docs/COMMIT_GUIDELINES.md"
  exit 1
fi

echo "OK: no editor/assistant signatures in tracked files."
